"""add_google_calendar_fields

Revision ID: e4cd5cddcaa1
Revises: d57998674c8a
Create Date: 2026-01-06 21:34:56.488873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4cd5cddcaa1'
down_revision: Union[str, None] = 'd57998674c8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('google_token_encrypted', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('google_refresh_token_encrypted', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('google_calendar_id', sa.String(), nullable=True))
    op.add_column('time_entries', sa.Column('google_event_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_entries', 'google_event_id')
    op.drop_column('employees', 'google_calendar_id')
    op.drop_column('employees', 'google_refresh_token_encrypted')
    op.drop_column('employees', 'google_token_encrypted')
    # ### end Alembic commands ###
